[build]
target = "riscv64imac-unknown-none-elf"
rustflags = ["-C", "link-args=-Tsrc/linker-script.lds"]

[target.riscv64imac-unknown-none-elf]
runner = [
    "qemu-system-riscv64",
    "-machine", "virt",
    "-cpu", "rv64",
    "-smp", "1",
    "-m", "128M",
    "-serial", "mon:stdio",
    "-nographic",
    # "-d", "int,guest_errors,unimp",
    # "-s", "-S",
    "-kernel"
]

[unstable]
build-std = ["core", "compiler_builtins", "panic_abort", "alloc"]
